DROP TABLE "EVENT";
DROP TABLE "COMMENT";
DROP TABLE "STUDENT_CLASS";
DROP TABLE "STUDENT";
DROP TABLE "NOTICE";
DROP TABLE "PROFESSOR_CLASS";
DROP TABLE "CLASS";
DROP TABLE "PROFESSOR";
DROP TABLE "DEPARTMENT";
DROP TABLE "PROFESSOR_LEVEL";








CREATE TABLE "PROFESSOR_LEVEL" (
	"PROFESSOR_LEVEL"	VARCHAR2(20)		NOT NULL
);



CREATE TABLE "PROFESSOR" (
	"PROFESSOR_NO"	VARCHAR2(20)		NOT NULL,
	"PROFESSOR_NAME"	VARCHAR2(40)		NOT NULL,
	"PROFESSOR_PHONE"	VARCHAR2(20)		NULL,
	"PROFESSOR_LEVEL"	VARCHAR2(20)		NOT NULL,
	"DEPARTMENT_NO"	VARCHAR2(10)		NOT NULL,
	"PROFESSOR_PWD"	VARCHAR2(50)		NOT NULL
);



CREATE TABLE "CLASS" (
	"CLASS_NO"	VARCHAR2(10)		NOT NULL,
	"CLASS_NAME"	VARCHAR2(60)		NOT NULL,
	"DEPARTMENT_NO"	VARCHAR2(10)		NOT NULL
);



CREATE TABLE "DEPARTMENT" (
	"DEPARTMENT_NO"	VARCHAR2(10)		NOT NULL,
	"DEPARTMENT_NAME"	VARCHAR(255)		NOT NULL,
	"CAPACITY"	VARCHAR(255)		NULL
);



CREATE TABLE "STUDENT" (
	"STUDENT_NO"	VARCHAR2(20)		NOT NULL,
	"STUDENT_NAME"	VARCHAR2(40)		NOT NULL,
	"STUDENT_PHONE"	VARCHAR2(20)		NOT NULL,
	"STUDENT_ADDRESS"	VARCHAR2(200)		NULL,
	"DEPARTMENT_NO"	VARCHAR2(10)		NOT NULL,
	"STUDENT_PWD"	VARCHAR2(50)		NOT NULL
);



CREATE TABLE "PROFESSOR_CLASS" (
	"PROFESSOR_NO"	VARCHAR2(20)		NOT NULL,
	"CLASS_NO"	VARCHAR2(10)		NOT NULL
);



CREATE TABLE "STUDENT_CLASS" (
	"STUDENT_NO"	VARCHAR2(20)		NOT NULL,
	"CLASS_NO"	VARCHAR2(10)		NOT NULL
);



CREATE TABLE "NOTICE" (
	"NOTICE_NO"	NUMBER		NOT NULL,
	"NOTICE_TITLE"	VARCHAR2(300)		NOT NULL,
	"NOTICE_CONTENT"	VARCHAR2(4000)		NULL,
	"NWRITTEN_TIME"	TIMESTAMP		NOT NULL,
	"WRITER"	VARCHAR2(20)		NOT NULL
);



CREATE TABLE "COMMENT" (
	"COMMENT_NO"	NUMBER		NOT NULL,
	"CWRITTEN_TIME"	TIMESTAMP		NOT NULL,
	"NOTICE_NO"	NUMBER		NOT NULL,
	"COMMENTER"	VARCHAR2(300)		NOT NULL
);



CREATE TABLE "EVENT" (
	"EVENT_NO"	NUMBER		NOT NULL,
	"EVENT_SD"	DATE		NOT NULL,
	"EVENT_ED"	DATE		NOT NULL,
	"EVENT_TITLE"	VARCHAR2(300)		NOT NULL,
	"EVENT_CONTENT"	VARCHAR2(1000)		NULL
);

ALTER TABLE "PROFESSOR_LEVEL" ADD CONSTRAINT "PK_PROFESSOR_LEVEL" PRIMARY KEY (
	"PROFESSOR_LEVEL"
);

ALTER TABLE "PROFESSOR" ADD CONSTRAINT "PK_PROFESSOR" PRIMARY KEY (
	"PROFESSOR_NO"
);

ALTER TABLE "CLASS" ADD CONSTRAINT "PK_CLASS" PRIMARY KEY (
	"CLASS_NO"
);

ALTER TABLE "DEPARTMENT" ADD CONSTRAINT "PK_DEPARTMENT" PRIMARY KEY (
	"DEPARTMENT_NO"
);

ALTER TABLE "STUDENT" ADD CONSTRAINT "PK_STUDENT" PRIMARY KEY (
	"STUDENT_NO"
);

ALTER TABLE "PROFESSOR_CLASS" ADD CONSTRAINT "PK_PROFESSOR_CLASS" PRIMARY KEY (
	"PROFESSOR_NO",
	"CLASS_NO"
);

ALTER TABLE "STUDENT_CLASS" ADD CONSTRAINT "PK_STUDENT_CLASS" PRIMARY KEY (
	"STUDENT_NO",
	"CLASS_NO"
);

ALTER TABLE "NOTICE" ADD CONSTRAINT "PK_NOTICE" PRIMARY KEY (
	"NOTICE_NO"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "PK_COMMENT" PRIMARY KEY (
	"COMMENT_NO"
);

ALTER TABLE "EVENT" ADD CONSTRAINT "PK_EVENT" PRIMARY KEY (
	"EVENT_NO"
);

ALTER TABLE "PROFESSOR" ADD CONSTRAINT "FK_PROFESSOR_LEVEL_TO_PROFESSOR_1" FOREIGN KEY (
	"PROFESSOR_LEVEL"
)
REFERENCES "PROFESSOR_LEVEL" (
	"PROFESSOR_LEVEL"
);

ALTER TABLE "PROFESSOR" ADD CONSTRAINT "FK_DEPARTMENT_TO_PROFESSOR_1" FOREIGN KEY (
	"DEPARTMENT_NO"
)
REFERENCES "DEPARTMENT" (
	"DEPARTMENT_NO"
);

ALTER TABLE "CLASS" ADD CONSTRAINT "FK_DEPARTMENT_TO_CLASS_1" FOREIGN KEY (
	"DEPARTMENT_NO"
)
REFERENCES "DEPARTMENT" (
	"DEPARTMENT_NO"
);

ALTER TABLE "STUDENT" ADD CONSTRAINT "FK_DEPARTMENT_TO_STUDENT_1" FOREIGN KEY (
	"DEPARTMENT_NO"
)
REFERENCES "DEPARTMENT" (
	"DEPARTMENT_NO"
);

ALTER TABLE "PROFESSOR_CLASS" ADD CONSTRAINT "FK_PROFESSOR_TO_PROFESSOR_CLASS_1" FOREIGN KEY (
	"PROFESSOR_NO"
)
REFERENCES "PROFESSOR" (
	"PROFESSOR_NO"
);

ALTER TABLE "PROFESSOR_CLASS" ADD CONSTRAINT "FK_CLASS_TO_PROFESSOR_CLASS_1" FOREIGN KEY (
	"CLASS_NO"
)
REFERENCES "CLASS" (
	"CLASS_NO"
);

ALTER TABLE "STUDENT_CLASS" ADD CONSTRAINT "FK_STUDENT_TO_STUDENT_CLASS_1" FOREIGN KEY (
	"STUDENT_NO"
)
REFERENCES "STUDENT" (
	"STUDENT_NO"
);

ALTER TABLE "STUDENT_CLASS" ADD CONSTRAINT "FK_CLASS_TO_STUDENT_CLASS_1" FOREIGN KEY (
	"CLASS_NO"
)
REFERENCES "CLASS" (
	"CLASS_NO"
);

ALTER TABLE "NOTICE" ADD CONSTRAINT "FK_PROFESSOR_TO_NOTICE_1" FOREIGN KEY (
	"WRITER"
)
REFERENCES "PROFESSOR" (
	"PROFESSOR_NO"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_NOTICE_TO_COMMENT_1" FOREIGN KEY (
	"NOTICE_NO"
)
REFERENCES "NOTICE" (
	"NOTICE_NO"
);

COMMIT;